### ISSUE TITLE
Timeout error in mutePublishedTrack 

### ISSUE THREAD

**Issue by ShubhamJuIT** [livekit/server-sdk-kotlin#6] opened 2023-03-05 18:28 UTC
**Describe the bug**
I am trying to mute audio of remote participant  using mutePublishedTrack but i everytime i am getting timout eror

**Expected behavior**
It should return success or error if anything goes wrong on livekit server

**Device Info:**
 - Java Version: [e.g. Java 11]
 - LiveKit Server SDK version: [e.g. 0.4.0]

**Additional context**
NA

**Comment by davidzhao** [comment] 2023-03-06 01:19
@ShubhamJuIT please include snippet of the call you are making. are you using LiveKit Cloud?

**Comment by ShubhamJuIT** [comment] 2023-03-06 01:28
Here is my code snippet. Yes i am using livekit cloud.

`    public LivekitModels.TrackInfo mutePublishedTrack(LivekitRoom.MuteRoomTrackRequest request) {
        Call<LivekitModels.TrackInfo> call = liveKitClient.mutePublishedTrack(request.getRoom(), request.getIdentity(), request.getTrackSid(), request.getMuted());
        try {
            Response<LivekitModels.TrackInfo> response = call.execute();
            LivekitModels.TrackInfo rooms = response.body();
            return rooms;
        } catch (IOException e) {
            log.error("Exception in muting participant", e);
            return null;
        }
    }`

**Comment by ShubhamJuIT** [comment] 2023-03-06 01:28
Here is my code snipppet. Yes i am using livekit cloud.

    public LivekitModels.TrackInfo mutePublishedTrack(LivekitRoom.MuteRoomTrackRequest request) {
        Call<LivekitModels.TrackInfo> call = liveKitClient.mutePublishedTrack(request.getRoom(), request.getIdentity(), request.getTrackSid(), request.getMuted());
        try {
            Response<LivekitModels.TrackInfo> response = call.execute();
            LivekitModels.TrackInfo rooms = response.body();
            return rooms;
        } catch (IOException e) {
            log.error("Exception in muting participant", e);
            return null;
        }
    }

**Comment by davidliu** [comment] 2023-03-26 13:09
@ShubhamJuIT this seems like either a connectivity issue or a livekit cloud issue. Closing since it can't be reproduced locally.

**Closed by davidliu** 2023-03-26 13:09 UTC
Labels: bug
